swagger: "2.0"
info:
  version: "0.0.1"
  title: QuanLySanBay
# during dev, should point to your local machine
host: localhost:10011
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /sanbay:
    x-swagger-router-controller: airports
    get:
      operationId: getToFromAiportAll
      description: Lấy danh sách tất cả các sân bay example - GET http://139.162.58.193:10011/sanbay | GET http://139.162.58.193:10011/sanbay?masanbaydi=HAN&truong=id%2Cname%2Ccity
      parameters:
        - name: masanbaydi
          type: string
          in: query
          description: Mã sân bay đi để tìm kiếm san bay đến tương ứng
          required: false
        - name: truong
          type: string
          in: query
          description: Trường dữ liệu cần trả về mặc định là id trường dữ liệu có thể là "id,name,city, region"
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetAirportResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /chuyenbay:
    x-swagger-router-controller: flights
    get:
      operationId: getFlight
      description: Lấy danh sách các chuyên bay VD - GET http://139.162.58.193:10011/chuyenbay?masanbaydi=HAN&masanbayden=SGN&ngaydi=1477388586&ngayve=1477388586&hang=Y&mucgia=E&soluongghe=1
      parameters:
        - name: masanbaydi
          type: string
          in: query
          description: Mã sân bay đi
          required: false
        - name: masanbayden
          type: string
          in: query
          description: Mã sân bay đến
          required: false
        - name: ngaydi
          type: number
          in: query
          description: TimeStamp ngày đi
          required: false
        - name: ngayve
          type: number
          in: query
          description: TimeStamp ngày về nếu là tìm kiếm khứ hổi
          required: false
        - name: hang
          type: string
          in: query
          description: Hạng vé "C" là phổ thông "Y" là thương gia
          required: false
        - name: mucgia
          type: string
          in: query
          description: Mức giá của vé mặc định là tất cả "E,F,G"
          required: false
        - name: soluongghe
          type: number
          in: query
          description: Số lượng ghế tìm kiếm mặc định là 1
          required: false
        - name: batdau
          type: number
          in: query
          description: Chi so chuyen bay bat dau
          required: false
        - name: ketthuc
          type: number
          in: query
          description: Chi so chuyen bay ket thuc
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/FindFlightResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: insertFlight
      description: Thêm chuyến bay 
      parameters:
      - name: token
        type: string
        in: query
        description: Token key
        required: true
      - name: chuyenbay
        in: body
        description: chuyến bay thêm vào
        required: true
        schema:
          $ref: "#/definitions/FlightInfo"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/FlightInfoRespone"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
        operationId: updateFlight
        description: Cập nhật chuyến bay
        parameters:
        - name: machuyenbay
          type: string
          in: query
          description: Mã chuyến bay
          required: true
        - name: masanbaydi
          type: string
          in: query
          description: Mã sân bay đi
          required: true
        - name: masanbayden
          type: string
          in: query
          description: Mã sân bay đến
          required: true
        - name: ngaydi
          type: number
          in: query
          description: TimeStamp ngày đi
          required: true
        - name: hang
          type: string
          in: query
          description: Hạng vé "C" là phổ thông "Y" là thương gia
          required: true
        - name: mucgia
          type: string
          in: query
          description: Mức giá của vé mặc định là tất cả "E,F,G"
          required: true
        - name: chuyenbay
          in: body
          description: chuyến bay thêm vào
          required: true
          schema:
            $ref: "#/definitions/FlightInfo"
        - name: token
          type: string
          in: query
          description: Token key
          required: true
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/FlightInfoRespone"
          "404":
            description: Failure
            schema:
              $ref: "#/definitions/ErrorResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: deleteFlight
      description: Xoá chuyến bay
      parameters:
      - name: machuyenbay
        type: string
        in: query
        description: Mã chuyến bay
        required: true
      - name: masanbaydi
        type: string
        in: query
        description: Mã sân bay đi
        required: true
      - name: masanbayden
        type: string
        in: query
        description: Mã sân bay đến
        required: true
      - name: ngaydi
        type: number
        in: query
        description: TimeStamp ngày đi
        required: true
      - name: hang
        type: string
        in: query
        description: Hạng vé "C" là phổ thông "Y" là thương gia
        required: true
      - name: mucgia
        type: string
        in: query
        description: Mức giá của vé mặc định là tất cả "E,F,G"
        required: true
      - name: token
        type: string
        in: query
        description: Token key
        required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/FlightInfoRespone"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"          
  /chuyenbay/{machuyenbay}:
    x-swagger-router-controller: flights
    get:
      operationId: getFlightInfo
      description: Lấy thông tin chuyên bay với mã chuyến bay và ngày đi example - GET http://139.162.58.193:10011/chuyenbay/DB589?ngaydi=1477440000
      parameters:
      - name: machuyenbay
        type: string
        in: path
        description: Mã chuyến bay
        required: true
      - name: ngaydi
        type: string
        in: query
        description: Ngày đi
        required: true
      - name: truong
        type: string
        in: query
        description: Trường dữ liệu cần trả về mặc định là id trường dữ liệu có thể là "machuyenbay,masanbaydi,masanbayden,ngaydi,giodi,hang,mucgia,soluongghe, khachhang"
        required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /chungthuc:
    x-swagger-router-controller: authenticate
    post:
      operationId: authenticate
      description: Đăng nhập
      parameters:
      - name: authenticate
        in: body
        description: username password
        required: true
        schema:
          $ref: "#/definitions/UserInfo"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /datcho:
    x-swagger-router-controller: book
    get:
      operationId: getBooks
      description: Lấy danh sách tất cả mã đặt chỗ example - GET http://139.162.58.193:10011/datcho?machuyenbay=DB589&ngaydi=1477440000&hang=C&mucgia=E
      parameters:
      - name: machuyenbay
        in: query
        type: string
        required: false
      - name: ngaydi
        in: query
        type: number
        required: false
      - name: hang
        in: query
        type: string
        required: false
      - name: mucgia
        in: query
        type: string
        required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BookArrayResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
    put: 
      operationId: updateInfoTicket
      description: Cập nhật thông tin mã đặt chỗ
      parameters:
        - name: datcho
          in: body 
          description: Mã đặt chỗ đã được cấp ở POST c
          required: true
          schema:
            $ref: "#/definitions/BookUpdateParameter"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BookValidateResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: bookTicket
      description: Tạo mã đặt chỗ với thông tin chuyến bay. Mã đặt chỗ được phát sinh tự động với trạng thái là đang chờ
      parameters:
        - name: datcho
          in: body
          description: thông tin đặt chỗ
          required: true
          schema:
            $ref: "#/definitions/BookPost"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BookResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /datcho/{madatcho}/:
    x-swagger-router-controller: book
    get: 
      operationId: getBookInfo
      description: Lây thông tin mã đặt chỗ với mã đặt chỗ truyền vào example - http://139.162.58.193:10011/datcho/FX124X/
      parameters:
        - name: madatcho
          type: string
          in: path
          description: Mã đặt chỗ được cấp ở Đặt chỗ 
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BookInfoResponse"
        "404":
          description: Failure
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  
  # Lấy danh sách các sân bay đi
  GetAirportResponse:
    required:
      - sanbay
    properties:
      sanbay:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: example SGN
            name:
              type: string
              description: example Sân bay Tan Son Nhat
            city:
              type: string
              description: example Ho Chi Minh
            region:
              type: string
              description: example Noi Dia
    example:
      sanbay: [{
          id: HNH,
          name: Noi Bai,
          city: Ha Noi,
          region: Noi Dia,
        }]
  FindFlightResponse:
    properties:
      chuyenbay:
        type: object
        properties:
          chuyendi:
            type: array
            items:
              type: object
              properties:
                machuyenbay:
                  type: string
                masanbaydi:
                  type: string
                masanbayden:
                  type: string
                ngaykhoihanh:
                  type: string
                  description: YYYY-DD-MM
                giokhoihanh:
                  type: string
                  description: HH:mm
                hang:
                  type: string
                mucgia:
                  type: string
          chuyenve:
            type: array
            items:
              type: object
              properties:
                machuyenbay:
                  type: string
                masanbaydi:
                  type: string
                masanbayden:
                  type: string
                ngaykhoihanh:
                  type: string
                  description: YYYY-DD-MM-Otz
                giokhoihanh:
                  type: string
                  description: HH:mm
                hang:
                  type: string
                mucgia:
                  type: string
    example:
      chuyendi: [{
          machuyenbay: DB589,
          masanbaydi: BMV,
          masanbayden: DIN,
          ngaykhoihanh: 2016-10-25T17:00:00.000Z,
          giokhoihanh: 12h,
          hang: Y,
          mucgia: E,
        }]
      chuyenve: [{
          machuyenbay: DB589,
          masanbaydi: BMV,
          masanbayden: DIN,
          ngaykhoihanh: 2016-10-25T17:00:00.000Z,
          giokhoihanh: 12h,
          hang: C,
          mucgia: G,
        }]
  FlightInfoRespone:
  
    properties:
      chuyenbay:
        type: object
        properties:
          machuyenbay:
            type: string
          masanbaydi:
            type: string
          masanbayden:
            type: string
          ngaydi:
            type: number
            description: timestamp unix
          giodi:
            type: number
            description: timestamp unix
          hang:
            type: string
          muc:
            type: string
          soghe:
            type: string
          giaban:
            type: string
      message:
        type: string
  FlightInfo:
    required:
      - chuyenbay
    properties:
      chuyenbay:
        type: object
        properties:
          machuyenbay:
            type: string
          masanbaydi:
            type: string
          masanbayden:
            type: string
          ngaydi:
            type: number
            description: timestamp unix
          giodi:
            type: number
            description: timestamp unix
          hang:
            type: string
          muc:
            type: string
          soghe:
            type: string
          giaban:
            type: string
  FlightResponse:
    properties:
      chuyenbay:
        type: array
        items:
          type: object
          properties:
            machuyenbay:
              type: string
            masanbaydi:
              type: string
            masanbayden:
              type: string
            ngaydi:
              type: string
              description: YYYY-DD-MM
            giodi:
              type: string
              description: HH:mm
            hang:
              type: string
            mucgia:
              type: string
            hanhkhach:
              type: array
              items:
                type: object
                properties:
                  madatcho:
                    type: string
                  danhxung:
                    type: string
                  ho:
                    type: string
                  ten:
                    type: string
    example:
      chuyendi: [
          machuyenbay: DB589,
          masanbaydi: BMV,
          masanbayden: DIN,
          ngaydi: 2016-10-25T17:00:00.000Z,
          giodi: 12h,
          hang: Y,
          mucgia: E,
          hanhkhach: [{
              madatcho: YY123X,
              danhxung: Ong,
              ho: ho,
              ten: ten,
            }]
        ]  
  BookResponse:
    required:
      - datcho
    properties:
      datcho:
        type: object
        properties:
          madatcho:
            type: string
          machuyenbay:
            type: string
          ngaydi:
            type: string
            description: YYYY-DD-MM
          thoigiancapphat:
            type: number
            description: thời gian timestamp cap phat
          thoihansudung:
            type: number
            description: thoi han timestamp su dung
    example:
      datcho: {
        madatcho: AS23A9,
        machuyenbay: FX100,
        ngaydi: 2016-21-10,
        thoigiancapphat: 1477388586,
        thoihansudung: 1477391586,
      }
  BookArrayResponse:
    properties:
      datcho:
        type: array
        items:
          type: object
          properties:
            madatcho:
              type: string
            machuyenbay:
              type: string
            ngay:
              type: number
              description: YYYY-DD-MM
            hang:
              type: string
            mucgia:
              type: string
            soghe:
              type: number
            gia:
              type: string
            trangthai:
              type: number
    example:
      datcho: [{
        madatcho: AS23A9,
        machuyenbay: FX100,
        ngay: 2016-21-10,
        hang: Y,
        mucgia: E,
        soghe: 1,
        gia: 100000,
        trangthai: 0,
      }]
  BookInfoResponse:
    properties:
      thongtindatcho:
        type: array
        items:
          type: object
          properties:
            madatcho:
              type: string
            machuyenbay:
              type: string
            ngaydi:
              type: string
            hang:
              type: string
            mucgia:
              type: string
            gia:
              type: string
            trangthai:
              type: number
            hanhkhach:
              type: array
              items:
                type: object
                properties:
                  danhxung:
                    type: string
                  ho:
                    type: string
                  ten:
                    type: string
    example:
      thongtindatcho: [{
            madatcho: AS23A9,
            machuyenbay: FX100,
            ngay: 2016-21-10,
            hang: Y,
            mucgia: E,
            soghe: 1,
            gia: 100000,
            trangthai: 0,
            hanhkhach: [{
                danhxung: Ong,
                ho: ho,
                ten: ten,
              }]
        }]
  BookPost:
    required:
      - datcho
    properties:
      datcho:
        type: object
        properties:
            machuyenbay:
              type: string
            ngaydi:
              type: number
            hang:
              type: string
            mucgia:
              type: string
            soghe:
              type: number
        
  BookUpdateParameter:
    required:
      - datcho
    properties:
      datcho:
        type: object
        properties:
          madatcho:
            type: string
          hanhkhach:
            type: array
            items:
              type: object
              properties:
                danhxung:
                  type: string
                ho:
                  type: string
                ten:
                  type: string
    example:
      datcho: {
        madatcho: AS23A9,
        hanhkhach: [{
                danhxung: Ong,
                ho: ho,
                ten: ten,
              }]
      }
  BookValidateResponse:
    properties:
      datcho:
        type: object
        properties:
          madatcho: 
            type: string
          machuyenbay:
            type: string
          masanbaydi:
            type: string
          masanbayden:
            type: string
          ngaydi:
            type: string
          giodi:
            type: string
          hang:
            type: string
          mucgia:
            type: string
          soghe:
            type: number
          tongtien:
            type: number
          trangthai:
            type: number
          hanhkhach:
            type: array
            items:
              type: object
              properties:
                danhxung:
                  type: string
                ho:
                  type: string
                ten:
                  type: string
    example:
      datcho: {
        madatcho: FX129X,
        machuyenbay: FX100,
        masanbaydi: SGN,
        masanbayden: HAN,
        ngaydi: 2016-10-26,
        giodi: 10:45,
        hang: Y,
        mucgia: C,
        soghe: 2,
        tongtien: 100000,
        trangthai: 1,
        hanhkhach: [
            {
               danhxung: Ong,
                ho: ho,
                ten: ten,
            },
            {
               danhxung: OngX,
                ho: hoX,
                ten: tenX,
            },
          ]
      }
  UserInfo:
    required:
      - user
    properties:
      user: 
        type: object
        properties:
          username:
            type: string
          password:
            type: string
  ErrorResponse:
    properties:
      message:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string



